[package]
name = "active-ttl-cache"
version = "0.1.0"
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
publish = false
edition = "2018"

[dependencies]
byteorder = "1.3.1"
crossbeam-channel = "0.3.8"
